import { Module } from '@nestjs/common';
import {
  AccountDeletionModule,
  AuthModule,
  BotApplicationModule,
  BudgetModule,
  CustomCategoryModule,
  ExportTransactionsModule,
  GenerateDashboardModule,
  GenerateReportModule,
  LoanModule,
  SearchTransactionsModule,
  UserSettingsModule,
} from '@afa/application';
import {
  AccountDeletionConfirmationRepositoryModule,
  AccountRepositoryModule,
  BudgetRepositoryModule,
  CategoryRepositoryModule,
  CommitIdempotencyLockRepositoryModule,
  ConversationStateRepositoryModule,
  CounterpartyRepositoryModule,
  CurrencyRepositoryModule,
  CustomCategoryWizardStateRepositoryModule,
  DebtRepositoryModule,
  DraftRepositoryModule,
  ExpenseHistoryRepositoryModule,
  ExportQueryRepositoryModule,
  FxRateRepositoryModule,
  LlmProviderModule,
  LoanRepositoryModule,
  LoanWizardStateRepositoryModule,
  ObjectStorageModule,
  OcrExtractionQueueRepositoryModule,
  ReportCacheRepositoryModule,
  ReportQueryRepositoryModule,
  SearchSessionRepositoryModule,
  TransactionAuditLogRepositoryModule,
  TransactionRepositoryModule,
  UserPreferenceRepositoryModule,
  UserRepositoryModule,
  VoiceTranscriptionQueueRepositoryModule,
  XlsxGeneratorModule,
} from '@afa/infrastructure';

import { EnvironmentBlockedProvidersModule } from '../providers/environment-blocked-providers.module';
import { ExtractionModelConfigModule } from '../providers/extraction-model-config.module';
import { TransactionCommitProviderModule } from '../providers/transaction-commit-provider.module';
import { TelegramWebhookController } from '../webhook/telegram-webhook.controller';
import { TelegramUpdateDedupService } from '../webhook/telegram-update-dedup.service';
import { NotificationDeliveryModule } from '../notifications/notification-delivery.module';
import { TelegramBotService } from './telegram-bot.service';

@Module({
  imports: [
    AuthModule,
    UserRepositoryModule,
    BotApplicationModule,
    ConversationStateRepositoryModule,
    TransactionRepositoryModule,
    CurrencyRepositoryModule,
    CategoryRepositoryModule,
    TransactionAuditLogRepositoryModule,
    DraftRepositoryModule,
    ExpenseHistoryRepositoryModule,
    DebtRepositoryModule,
    CounterpartyRepositoryModule,
    VoiceTranscriptionQueueRepositoryModule,
    OcrExtractionQueueRepositoryModule,
    CommitIdempotencyLockRepositoryModule,
    ObjectStorageModule,
    LlmProviderModule,
    ExtractionModelConfigModule,
    TransactionCommitProviderModule,
    EnvironmentBlockedProvidersModule,
    NotificationDeliveryModule,
    BudgetModule,
    BudgetRepositoryModule,
    AccountRepositoryModule,
    FxRateRepositoryModule,
    LoanModule,
    LoanRepositoryModule,
    LoanWizardStateRepositoryModule,
    GenerateReportModule,
    ReportQueryRepositoryModule,
    ReportCacheRepositoryModule,
    GenerateDashboardModule,
    SearchTransactionsModule,
    SearchSessionRepositoryModule,
    AccountDeletionModule,
    AccountDeletionConfirmationRepositoryModule,
    ExportTransactionsModule,
    ExportQueryRepositoryModule,
    XlsxGeneratorModule,
    UserSettingsModule,
    UserPreferenceRepositoryModule,
    CustomCategoryModule,
    CustomCategoryWizardStateRepositoryModule,
  ],
  controllers: [TelegramWebhookController],
  providers: [TelegramBotService, TelegramUpdateDedupService],
})
export class TelegramBotModule {}
