import { computeReportCachePeriods, type ReportPeriodType } from '../events/report-cache-period';
import type { ReportDateRange } from './report-query-types';

/**
 * TASK-REP-007/TASK-REP-001 (remaining scope) — pure date-range boundary
 * computation for the 5 fixed calendar periods this task caches
 * (Daily/Weekly/Monthly/Quarterly/Yearly). Monthly was originally out of
 * scope (blocked on TASK-FIN-002/003/004/008); `computeMonthlyBoundary`
 * below closes that gap now that all four are done — `ReportPeriodType`
 * already listed `'monthly'` from the start (TASK-DB-009's invalidation
 * side always covered it), only the generation-side boundary function was
 * missing.
 *
 * `periodKey` is deliberately NOT recomputed with fresh logic here — it
 * calls the exact same `computeReportCachePeriods` (`@afa/domain`,
 * TASK-DB-009) and picks out the matching entry, so a report generated by
 * this task is cached under precisely the key TASK-DB-009's own
 * invalidation consumer already knows how to delete. Duplicating the
 * key-string algorithm here would risk the two silently drifting apart.
 */
export interface FixedPeriodBoundary {
  readonly reportType: ReportPeriodType;
  readonly periodKey: string;
  readonly current: ReportDateRange;
  /** Same-length immediately-prior period, for comparison lines (FR-REP-006/§9.5.7). */
  readonly prior: ReportDateRange;
  readonly priorPeriodKey: string;
}

function periodKeyFor(date: Date, reportType: ReportPeriodType): string {
  return computeReportCachePeriods(date).find((p) => p.reportType === reportType)!.periodKey;
}

function startOfUtcDay(date: Date): Date {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
}

function addUtcDays(date: Date, days: number): Date {
  const result = new Date(date);
  result.setUTCDate(result.getUTCDate() + days);
  return result;
}

export function computeDailyBoundary(asOf: Date): FixedPeriodBoundary {
  const start = startOfUtcDay(asOf);
  const end = addUtcDays(start, 1);
  const priorStart = addUtcDays(start, -1);
  return {
    reportType: 'daily',
    periodKey: periodKeyFor(start, 'daily'),
    current: { start, end },
    prior: { start: priorStart, end: start },
    priorPeriodKey: periodKeyFor(priorStart, 'daily'),
  };
}

/** ISO 8601 week (Monday start), matching `report-cache-period.ts`'s own `toWeeklyPeriodKey` week-numbering exactly (both derive from the same `computeReportCachePeriods` call). */
export function computeWeeklyBoundary(asOf: Date): FixedPeriodBoundary {
  const day = startOfUtcDay(asOf);
  const isoDayNumber = (day.getUTCDay() + 6) % 7; // Monday=0..Sunday=6
  const start = addUtcDays(day, -isoDayNumber);
  const end = addUtcDays(start, 7);
  const priorStart = addUtcDays(start, -7);
  return {
    reportType: 'weekly',
    periodKey: periodKeyFor(start, 'weekly'),
    current: { start, end },
    prior: { start: priorStart, end: start },
    priorPeriodKey: periodKeyFor(priorStart, 'weekly'),
  };
}

export function computeMonthlyBoundary(asOf: Date): FixedPeriodBoundary {
  const year = asOf.getUTCFullYear();
  const month = asOf.getUTCMonth(); // 0..11
  const start = new Date(Date.UTC(year, month, 1));
  const end = new Date(Date.UTC(year, month + 1, 1));
  const priorStart = new Date(Date.UTC(year, month - 1, 1));
  return {
    reportType: 'monthly',
    periodKey: periodKeyFor(start, 'monthly'),
    current: { start, end },
    prior: { start: priorStart, end: start },
    priorPeriodKey: periodKeyFor(priorStart, 'monthly'),
  };
}

export function computeQuarterlyBoundary(asOf: Date): FixedPeriodBoundary {
  const year = asOf.getUTCFullYear();
  const quarterIndex = Math.floor(asOf.getUTCMonth() / 3); // 0..3
  const start = new Date(Date.UTC(year, quarterIndex * 3, 1));
  const end = new Date(Date.UTC(year, quarterIndex * 3 + 3, 1));
  const priorStart = new Date(Date.UTC(year, quarterIndex * 3 - 3, 1));
  return {
    reportType: 'quarterly',
    periodKey: periodKeyFor(start, 'quarterly'),
    current: { start, end },
    prior: { start: priorStart, end: start },
    priorPeriodKey: periodKeyFor(priorStart, 'quarterly'),
  };
}

export function computeYearlyBoundary(asOf: Date): FixedPeriodBoundary {
  const year = asOf.getUTCFullYear();
  const start = new Date(Date.UTC(year, 0, 1));
  const end = new Date(Date.UTC(year + 1, 0, 1));
  const priorStart = new Date(Date.UTC(year - 1, 0, 1));
  return {
    reportType: 'yearly',
    periodKey: periodKeyFor(start, 'yearly'),
    current: { start, end },
    prior: { start: priorStart, end: start },
    priorPeriodKey: periodKeyFor(priorStart, 'yearly'),
  };
}
